stages:
- API

.automation_job_template: &init
  script:
    - rm -rf caesar
    - git clone https://gitlab.com/karanc/caesar.git
    - cd caesar
    - npx mocha ./test/api/*.js --grep $TAG --reporter mocha-allure-reporter
    - allure generate allure-results  
  artifacts:
    when: always
    paths:
      - caesar/allure-report
      - caesar/openTestReport.command
  allow_failure: true
  when: manual
  tags:
    - k-runner 
SmokeTests:
   <<: *init
   stage: API
   variables:
    TAG: "@smoke"
RegressionTests:
    <<: *init
    stage: API
    variables:
     TAG: "@regression"